# Generated by Django 5.2.5 on 2025-09-02 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0002_student_account_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='user',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='to_account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='from_account',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Account',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
