# Generated by Django 5.2.5 on 2025-09-05 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0003_remove_account_user_remove_transaction_to_account_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Items',
            new_name='Item',
        ),
    ]
