# Generated by Django 5.2.5 on 2025-09-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0005_item_sold_seller'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sold',
            new_name='is_sold',
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
