# Generated by Django 5.2.5 on 2025-09-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0007_item_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
