# Generated by Django 5.2.5 on 2025-09-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0008_seller_wallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seller',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=200.0, max_digits=10),
        ),
    ]
