# Generated by Django 5.2.5 on 2025-09-18 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0010_alter_item_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.ImageField(default='car.jpeg', upload_to='item_image/'),
        ),
    ]
