# Generated by Django 6.0.4 on 2026-06-02 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0012_alter_item_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seller',
            name='shop_name',
        ),
    ]
