# Generated by Django 6.0.4 on 2026-06-08 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0014_item_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='seller',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='seller_profiles/'),
        ),
    ]
