# Generated by Django 6.0.4 on 2026-06-08 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seller', '0016_orders'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orders',
        ),
    ]
