# Generated by Django 5.2.5 on 2025-09-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=20000.0, max_digits=10),
        ),
    ]
