# Generated by Django 5.2.5 on 2025-09-16 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0002_alter_buyer_wallet_balance'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='item_name',
            new_name='title',
        ),
        migrations.RemoveField(
            model_name='purchase',
            name='amount',
        ),
        migrations.AddField(
            model_name='purchase',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
