# Generated by Django 5.2.5 on 2025-09-17 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0003_rename_item_name_purchase_title_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='price',
            new_name='amount',
        ),
    ]
