# Generated by Django 5.2.5 on 2025-09-17 05:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0004_rename_price_purchase_amount'),
        ('seller', '0010_alter_item_seller'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='title',
        ),
        migrations.AddField(
            model_name='purchase',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seller.item'),
            preserve_default=False,
        ),
    ]
