# Generated by Django 5.2.5 on 2025-09-17 06:02

import buyer.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0005_remove_purchase_title_purchase_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='order_number',
            field=models.CharField(default=buyer.models.generateOrderNumber, max_length=20, unique=True),
        ),
    ]
