# Generated by Django 5.2.5 on 2025-09-18 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0006_purchase_order_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buyer',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=50000.0, max_digits=10),
        ),
    ]
