# Generated by Django 5.2.5 on 2025-09-18 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0007_alter_buyer_wallet_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='item_image',
            field=models.ImageField(default='IMG-20250809-WA0009.jpg', upload_to='item_image/'),
        ),
    ]
