# Generated by Django 5.2.5 on 2025-09-18 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0008_purchase_item_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='item_image',
            field=models.ImageField(upload_to='item_image/'),
        ),
    ]
