# Generated by Django 5.2.5 on 2025-09-18 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0009_alter_purchase_item_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='item_image',
        ),
    ]
