# Generated by Django 6.0.4 on 2026-06-04 15:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0010_remove_purchase_item_image'),
        ('seller', '0014_item_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='buyer.buyer')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seller.item')),
            ],
        ),
    ]
