# Generated by Django 6.0.4 on 2026-06-06 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buyer', '0013_purchase_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='buyer',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='buyer_profiles/'),
        ),
        migrations.AlterField(
            model_name='buyer',
            name='wallet_balance',
            field=models.DecimalField(decimal_places=2, default=5000000.0, max_digits=10),
        ),
    ]
